name: React Todo App CI/CD

on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - run: npm install
      - run: npm run build

      - name: Upload Temp Build
        uses: actions/upload-artifact@v4
        with:
          name: temp-build
          path: build/

  trivy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.69.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.69.3_Linux-64bit.deb

      - name: Run Trivy Scan (FAIL if vulnerabilities found)
        run: |
          trivy fs . --severity HIGH,CRITICAL 

  approval_before_artifact:
    runs-on: ubuntu-latest
    needs: trivy
    environment:
      name: security-approval   # 👈 create this in GitHub (Required reviewers)
    steps:
      - run: echo "Waiting for approval after Trivy..."

  artifact:
    runs-on: ubuntu-latest
    needs: approval_before_artifact
    steps:
      - name: Download Temp Build
        uses: actions/download-artifact@v4
        with:
          name: temp-build
          path: build/

      - name: Upload Final Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/

  test:
    runs-on: ubuntu-latest
    needs: artifact
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - run: npm install
      - run: npm test -- --watchAll=false

  approval_after_test:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: test-approval   # 👈 required reviewers
    steps:
      - run: echo "Waiting for approval after test..."

  sonar:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - uses: actions/checkout@v4
 
     - name: SonarQube Scan
       uses: SonarSource/sonarqube-scan-action@v6
       continue-on-error: true                # <-- workflow continues even if quality is low
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       with:
         projectBaseDir: .
         args: >
           -Dsonar.projectKey=kuldeepdevda70_react-todo-app
           -Dsonar.organization=kuldeepdevda70
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
           -Dsonar.qualitygate.wait=true     # <-- wait for Quality Gate result
      

  deploy:
    runs-on: ubuntu-latest
    needs: [test, sonar, trivy]
    environment:
      name: ${{ github.ref == 'refs/heads/dev' && 'dev' || 'prod' }}
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: build/

      - name: Determine Environment
        id: env
        run: |
          ENV_INPUT="${{ github.event.inputs.environment }}"
          if [ -n "$ENV_INPUT" ]; then
            ENV="$ENV_INPUT"
          elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            ENV="dev"
          elif [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
            ENV="prod"
          fi
          echo "ENV=$ENV" >> $GITHUB_ENV
          if [ "$ENV" == "dev" ]; then
            echo "HOST=${{ secrets.DEV_HOST }}" >> $GITHUB_ENV
            SECRET_KEY="DEV_KEY"
          elif [ "$ENV" == "prod" ]; then
            echo "HOST=${{ secrets.PROD_HOST }}" >> $GITHUB_ENV
            SECRET_KEY="PROD_KEY"
          fi
          echo "SECRET_KEY=$SECRET_KEY" >> $GITHUB_ENV

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets[env.SECRET_KEY] }}

      - name: Deploy Build to Server
        run: |
          scp -o StrictHostKeyChecking=no -r build/* ubuntu@$HOST:/home/ubuntu/build/
          ssh -o StrictHostKeyChecking=no ubuntu@$HOST << 'EOF'
            sudo apt update
            sudo apt install nginx -y
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/build/* /var/www/html/
            sudo systemctl restart nginx
          EOF


          